//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodChem
    {
        public long recNO { get; set; }
        public string bloodChemID { get; set; }
        public string labID { get; set; }
        public Nullable<decimal> result { get; set; }
        public string LabTestGroupID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
        public string personnelID { get; set; }
    }
}
