//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodPressure
    {
        public long recNo { get; set; }
        public string BPID { get; set; }
        public string vSignID { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<int> systolic { get; set; }
        public Nullable<int> diastolic { get; set; }
        public Nullable<int> pulseRate { get; set; }
    }
}
