//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodChem
    {
        public long recNO { get; set; }
        public string bloodChemID { get; set; }
        public string labID { get; set; }
        public Nullable<decimal> fbs { get; set; }
        public Nullable<decimal> serumUricAcid { get; set; }
        public Nullable<decimal> creatinine { get; set; }
        public Nullable<decimal> cholesterol { get; set; }
        public Nullable<decimal> triglycerides { get; set; }
        public Nullable<decimal> hdl { get; set; }
        public Nullable<decimal> ldl { get; set; }
        public Nullable<decimal> vldl { get; set; }
        public Nullable<decimal> sgpt { get; set; }
        public Nullable<decimal> sgot { get; set; }
        public Nullable<decimal> bun { get; set; }
        public Nullable<decimal> potassium { get; set; }
        public Nullable<decimal> sodium { get; set; }
        public Nullable<decimal> chloride { get; set; }
        public Nullable<decimal> calcium { get; set; }
        public Nullable<decimal> glycosylatedHemoglobin { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
        public string personnelID { get; set; }
        public string pathologist { get; set; }
        public string medtech { get; set; }
    }
}
