//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBC
    {
        public long recNO { get; set; }
        public string cbcID { get; set; }
        public string labID { get; set; }
        public Nullable<decimal> wbc { get; set; }
        public Nullable<decimal> neu { get; set; }
        public Nullable<decimal> lym { get; set; }
        public Nullable<decimal> mon { get; set; }
        public Nullable<decimal> eos { get; set; }
        public Nullable<decimal> bas { get; set; }
        public Nullable<decimal> rbc { get; set; }
        public Nullable<decimal> hgb { get; set; }
        public Nullable<decimal> hct { get; set; }
        public Nullable<decimal> mcv { get; set; }
        public Nullable<decimal> mch { get; set; }
        public Nullable<decimal> mchc { get; set; }
        public Nullable<decimal> plt { get; set; }
        public string personnelID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
    }
}
