//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMun
    {
        public string id { get; set; }
        public string psgcCode { get; set; }
        public string citymunDesc { get; set; }
        public string regDesc { get; set; }
        public string provCode { get; set; }
        public string citymunCode { get; set; }
    }
}
