//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicPatientAppointment
    {
        public long recNo { get; set; }
        public string clinicAppID { get; set; }
        public string qrCode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> daytime { get; set; }
        public string serviceID { get; set; }
    }
}
