//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicUnavailability
    {
        public int recNo { get; set; }
        public string unavailableID { get; set; }
        public string personnelID { get; set; }
        public string serviceID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string justification { get; set; }
        public string cancelledByID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
    }
}
