//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditRemark
    {
        public long recNo { get; set; }
        public string editID { get; set; }
        public string labID { get; set; }
        public string remarks { get; set; }
        public string editedBy { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
    }
}
