//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fecalysi
    {
        public long recNo { get; set; }
        public string fecalysisID { get; set; }
        public string labID { get; set; }
        public string color { get; set; }
        public string otherColorDesc { get; set; }
        public string consistency { get; set; }
        public string otherConDesc { get; set; }
        public Nullable<short> pusFrom { get; set; }
        public Nullable<short> pusTo { get; set; }
        public Nullable<short> rbcFrom { get; set; }
        public Nullable<short> rbcTo { get; set; }
        public string fatGlobules { get; set; }
        public string bacteria { get; set; }
        public string otherFindings { get; set; }
    }
}
