//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryExam
    {
        public long recNo { get; set; }
        public string labID { get; set; }
        public string referralID { get; set; }
        public string labTestID { get; set; }
        public string otherLabDesc { get; set; }
        public string xrayDesc { get; set; }
        public string ultrasoundDesc { get; set; }
        public string ecgDesc { get; set; }
        public Nullable<bool> isTested { get; set; }
        public Nullable<bool> isEncoded { get; set; }
        public Nullable<System.DateTime> dateEncoded { get; set; }
        public string encodedBy { get; set; }
        public string personnelID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
    }
}
