//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaleRepro_Diagnosis
    {
        public long recNo { get; set; }
        public string MRDiagnosisID { get; set; }
        public string MRID { get; set; }
        public string PEfindings { get; set; }
        public string abdomen { get; set; }
        public string extGenita { get; set; }
        public Nullable<decimal> DREsize { get; set; }
        public Nullable<byte> consistency { get; set; }
        public Nullable<byte> texture { get; set; }
        public Nullable<byte> mobility { get; set; }
        public string lowbackPain { get; set; }
        public string arthriticPain { get; set; }
        public string rectalFinding { get; set; }
        public string TRUS { get; set; }
        public string PSA { get; set; }
        public string transperrinealBiopsy { get; set; }
        public string transrectalBiopsy { get; set; }
        public string TRUSBiopsy { get; set; }
        public string Remarks { get; set; }
    }
}
