//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRHrequest
    {
        public long recNo { get; set; }
        public string requestID { get; set; }
        public string referralID { get; set; }
        public Nullable<bool> isInterviewDone { get; set; }
        public string interviewerID { get; set; }
        public Nullable<System.DateTime> interviewDT { get; set; }
        public Nullable<bool> isDiagnoseDone { get; set; }
        public string diagPersonID { get; set; }
        public Nullable<System.DateTime> diagnoseDT { get; set; }
        public string requestPersonID { get; set; }
        public Nullable<System.DateTime> requestDT { get; set; }
    }
}
