//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public long recNo { get; set; }
        public string qrCode { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<bool> sex { get; set; }
        public string brgyCode { get; set; }
        public string address { get; set; }
        public string contactNo { get; set; }
        public string occupation { get; set; }
        public Nullable<System.DateTime> timeLog { get; set; }
        public string userID { get; set; }
        public Nullable<byte> registrationType { get; set; }
    }
}
