//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDiagnosi
    {
        public long recNo { get; set; }
        public string resultID { get; set; }
        public string consultID { get; set; }
        public string diagnoseID { get; set; }
        public string otherDiagnosis { get; set; }
        public string toothNum { get; set; }
    }
}
