//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Morbidity
    {
        public int recNo { get; set; }
        public string morbidityID { get; set; }
        public string diagnoseID { get; set; }
        public Nullable<int> male { get; set; }
        public Nullable<int> female { get; set; }
        public string type { get; set; }
    }
}
