//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployeeHealthWell
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public string idNo { get; set; }
        public string qrCode { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public string fullNameLast { get; set; }
        public string fullNameFirst { get; set; }
        public string fullNameTitle { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string sex { get; set; }
        public string civilStatCode { get; set; }
        public string positionTitle { get; set; }
        public string subPositionTitle { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public string employmentStatus { get; set; }
        public string shortDepartmentName { get; set; }
        public string departmentName { get; set; }
        public string brgyPermAddress { get; set; }
        public string cityMunPermAddress { get; set; }
        public string provincePermAddress { get; set; }
        public string ZIPPermAddress { get; set; }
        public string contactNo { get; set; }
    }
}
