//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray_Screening
    {
        public int recNo { get; set; }
        public string screeningID { get; set; }
        public string qrCode { get; set; }
        public Nullable<byte> manigarilyo { get; set; }
        public Nullable<byte> moInom { get; set; }
        public Nullable<bool> tbHistory { get; set; }
        public string kanusA { get; set; }
        public Nullable<bool> paryenteWithTB { get; set; }
        public string kinsa { get; set; }
        public string personnelID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
    }
}
