//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray_LabResult
    {
        public int recNo { get; set; }
        public string labResultID { get; set; }
        public string labRequestID { get; set; }
        public string laboratoryName { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
        public Nullable<bool> specimenQuality { get; set; }
        public string reason { get; set; }
        public string labSerialNo { get; set; }
        public Nullable<System.DateTime> dateSpecimenExamined { get; set; }
        public string xpertMTBRif { get; set; }
        public string smearMicroscopy_1 { get; set; }
        public string smearMicroscopy_1_1 { get; set; }
        public string smearMicroscopy_2 { get; set; }
        public string smearMicroscopy_2_1 { get; set; }
        public string performedBy_personnelID { get; set; }
        public string verifiedBy_personnelID { get; set; }
        public string notedBy_personnelID { get; set; }
        public string personnelID { get; set; }
        public string dateTimeLog { get; set; }
    }
}
