//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray_PersonStatus
    {
        public int recNo { get; set; }
        public string personStatusID { get; set; }
        public string screeningID { get; set; }
        public Nullable<bool> isXray { get; set; }
        public Nullable<bool> isNeedScutum { get; set; }
        public string personnelID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
        public string xrayResult { get; set; }
        public Nullable<System.DateTime> xrayResultDate { get; set; }
        public string xrayResultPersonnelID { get; set; }
        public Nullable<System.DateTime> xrayResultDateTimeLog { get; set; }
    }
}
