//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray_PersonComorbidity
    {
        public int recNo { get; set; }
        public string personComorbidityID { get; set; }
        public string screeningID { get; set; }
        public string comorbidityID { get; set; }
        public string otherComorbidity { get; set; }
    }
}
