//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray_ScutumLabRequest
    {
        public int recNo { get; set; }
        public string labRequestID { get; set; }
        public string personStatusID { get; set; }
        public string requestingFacility { get; set; }
        public Nullable<System.DateTime> dateOfRequest { get; set; }
        public Nullable<bool> treatmentHistory { get; set; }
        public Nullable<System.DateTime> dateOfTreatment { get; set; }
        public Nullable<bool> testRequested { get; set; }
        public Nullable<bool> collection { get; set; }
        public Nullable<System.DateTime> dateCollected { get; set; }
        public string preparedBy_personnelID { get; set; }
        public string personnelID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
    }
}
