//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xray_HouseMembers
    {
        public int recNo { get; set; }
        public string houseID { get; set; }
        public string name { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string qrCode { get; set; }
        public string personnelID { get; set; }
        public Nullable<System.DateTime> dateTimeLog { get; set; }
    }
}
